name: Review

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: true

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  review:
    env:
      GOPRIVATE: github.com/livingpackets/*
      GITHUB_TOKEN: ${{ secrets.DEPLOYBOT_TOKEN }}
    permissions:
      id-token: write
      contents: read
      issues: read
    runs-on: ubuntu-latest
    needs:
      - pr-labeler
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'
        cache: false

    - name: download modules and prerequisites
      run: |
        echo "machine github.com login livingpackets-deploybot password ${GITHUB_TOKEN} " >> ~/.netrc
        go mod download
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOYBOT_TOKEN }}
        GOPRIVATE: github.com/livingpackets/*

    - name: check outdated dependencies
      run: |
        go install github.com/psampaz/go-mod-outdated@latest
        go list -mod=readonly -u -m -json all | go-mod-outdated -direct -update -ci

    - uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        skip-cache: true
        args: --timeout=5m --exclude-dirs=docs


    # postgres!
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner
          POSTGRES_DB: testdb
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
